server:
  port: 8000

spring:
  profiles:
    active: dev
  mvc:
    servlet:
      load-on-startup: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间/毫秒，6小时  1小时 = 3600000 毫秒
  expiration: 21600000